apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-demo-config
  namespace: demos
data:
  NODE_ENV: production
  PORT: "5000"
  ENABLE_DOCS: "true"
  DB_HOST: auth-demo-postgres
  DB_PORT: "5432"
  DB_NAME: auth_demo
  DB_SSL: "false"
  ALLOWED_ORIGINS: "https://joannegton.com,https://auth-demo.joannegton.com"
