apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demos

resources:
  - namespace.yaml
  - configmap-demo.yaml
  - postgres-demo.yaml
  - deployment-demo.yaml
  - service-demo.yaml
  - ingressroute-demo.yaml
  - reset-cronjob.yaml

labels:
  - pairs:
      app: auth-demo
      environment: demo
      managed-by: kustomize
    includeSelectors: false
