name: Continuous Integration

on:
  push:
    branches: [main, master, dev]
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
